name: yatrasathi
description: "A smart travel and culture exploration app."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core & Backend
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  cloud_functions: ^4.5.5

  # Camera & Passport OCR (Google ML Kit)
  camera: ^0.10.5+9
  google_mlkit_text_recognition: ^0.11.0

  # Location Tracking
  geolocator: ^10.1.0

  # State Management & Media Utilities
  flutter_riverpod: ^2.4.9
  image_picker: ^1.2.2
  http: ^1.6.0
  flutter_tts: ^4.2.5
  translator: ^1.0.4+1
  panorama_viewer: ^2.0.7
  speech_to_text: ^7.4.0
  url_launcher: ^6.3.2
  model_viewer_plus: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Assets section
  # Note: Subdirectories must be explicitly listed with a trailing slash '/'
  assets:
    - assets/
    - assets/product/